# -*- coding: utf-8 -*-
"""kwanty.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IBLMDIt3HNnw2YkWIxEYMUmwx5FTM89D
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.special import sph_harm_y, genlaguerre
from math import factorial
from matplotlib.widgets import Slider

def hydrogen_wave_func(n, l, m, r, theta, phi):
    a0 = 1.0
    rho = 2 * r / (n * a0)  # zmienna bezwymiarowa
    norm_r = np.sqrt((2 / (n * a0))**3 * factorial(n - l - 1) / (2 * n * factorial(n + l))) #stała normalizacyjna
    laguerre = genlaguerre(n - l - 1, 2 * l + 1)
    radial = norm_r * np.exp(-rho / 2) * (rho**l) * laguerre(rho)  # część radialna
    angular = sph_harm_y(l, m, theta, phi) # Harmoniki sferyczne
    return radial * angular

# --- KONFIGURACJA ---
n, l, m = 3,2,1
grid_res = 500
limit = n**2 * 2.5
coords = np.linspace(-limit, limit, grid_res)
A, B = np.meshgrid(coords, coords)

# Tworzenie figury z automatycznym układem (constrained_layout)
fig, axes = plt.subplots(1, 3, figsize=(20, 6), facecolor='black', layout='constrained')

# Definicje płaszczyzn
# 1. XY (Z=0)
r_xy = np.sqrt(A**2 + B**2 + 1e-10)
theta_xy = np.arccos(0 / r_xy)  # pi/2
phi_xy = np.arctan2(B, A)

# 2. XZ (Y=0)
r_xz = np.sqrt(A**2 + B**2)
theta_xz = np.arccos(B / r_xz)
phi_xz = np.zeros_like(r_xz)

# 3. YZ (X=0)
r_yz = np.sqrt(A**2 + B**2 + 1e-10)
theta_yz = np.arccos(B / r_yz)
phi_yz = np.full_like(r_yz, np.pi/2)

planes = [
    (r_xy, theta_xy, phi_xy, "Płaszczyzna XY (z=0)", "x", "y"),
    (r_xz, theta_xz, phi_xz, "Płaszczyzna XZ (y=0)", "x", "z"),
    (r_yz, theta_yz, phi_yz, "Płaszczyzna YZ (x=0)", "y", "z")
]

for ax, (r, th, ph, title, xlab, ylab) in zip(axes, planes):
    psi = hydrogen_wave_func(n, l, m, r, th, ph)

    # Skalowanie potęgowe (wizualne), powinno być np.abs(psi)**2 ale wtedy gorzej wygląda na ekranie dlatego skalujemy przez spierwiastkowanie
    display_data = np.abs(psi)

    img = ax.imshow(display_data,
                    extent=[-limit, limit, -limit, limit],
                   #cmap='gist_earth',
                    origin='lower',
                    interpolation='bicubic')

    # Stylizacja osi i napisów
    ax.set_title(title, color='white', fontsize=14, pad=10)
    ax.set_xlabel(f"{xlab} [$a_0$]", color='gray')
    ax.set_ylabel(f"{ylab} [$a_0$]", color='gray')
    ax.tick_params(colors='gray', which='both')

    # Dodanie legendy (colorbar) do każdego subplota
    cb = fig.colorbar(img, ax=ax, shrink=0.7, pad=0.05)
    cb.ax.yaxis.set_tick_params(color='white')
    plt.setp(plt.getp(cb.ax.axes, 'yticklabels'), color='white')
    cb.set_label(r'(Gęstość prawdopodobieństwa)$^{\frac{1}{4}}$ $|\psi|^{\frac{1}{2}}$ [$m^{-\frac{1}{2}}$]', color='white', fontsize=12)

plt.suptitle(f"Model atomu wodoru - orbital |{n}, {l}, {m}",
            color="white", fontsize=22, y=1.05)

plt.show()